language: node_js
node_js:
- '0.10'
before_script:
- npm install -g protractor grunt-cli
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start
- grunt server  # start a Web server
- sleep 3
dadons:
  sauce_connect: true
cache:
  directories:
  - node_modules
env:
  global:
  - secure: bE5AxOCgoO3/VBpj4kMReZrzjfn4+V4A0qpyHGum0TGxMPLCKUZA/07ru6+hsauOUME/8DT+Zr/3q52e8CBT5aQBmOcCkz9JZiM5ONDj/ZXW7sFGUyqZaNpw+uHcLetR8qzx/0V1MjpOde/3lVMWVQSXOD15BmwrtmRnxKr7xVk=
  - secure: SeK8fz3BY7nnRoMEAL8miEqEX/J6ZGWNbiKgSEPugZ2M4LpERffdkBbMSbLLJgx1d11pl0eYd4ghszLOU7VSzmg366jSFWB54G77xVAcapI0kdN0uY6MNiQgSaRZ+hEWUhU0V4ANVFE4rTxY1otRxqANkmp9QMHkrLXBQU801fc=
