language: node_js
node_js:
- '0.10'
before_script:
- npm install -g
addons:
  sauce_connect: true
cache:
  directories:
    - node_modules
env:
  global:
  - secure: vlAfPVk9wYMLt3Q4DgvAUPpclJoTiNcaZnUVOMRFCPROt+9Rtn1C/IBvi897QmSEpsxUSDebr5fYAb675TmCD6z8RWLGcWUacdyKVjshfzhZdCLobdE2XkvBTF051QpM5so+xnTaYZZOTHFHuVVLzf9J/ujuMZBzvAGET3+M/gM=
  - secure: VLvHvOJ3OyEGEb4rt3qTyTjmrPwTQrkbmLgxFqEk5yHwHR7Y6qblR4fCSrOYlLhw/EeN8tOayCF+I4QhZHuMoX1mh3x5xxXskKH1h+YSmWOvO+svNEjvNGMvVX1igXx5a95hwp32LAWL7mDi886G5KLzn6ittjY++EPNAm/lcd8=
